import pygame

# MainMenu
PVSP_BUTTON = pygame.image.load("resources/images/pvsp.png")
PVSC_BUTTON = pygame.image.load("resources/images/pvsc.png")
SETTINGS_BUTTON = pygame.image.load("resources/images/settings.png")
EXIT_BUTTON = pygame.image.load("resources/images/exit.png")
HOVER_PVSP_BUTTON = pygame.image.load("resources/images/hover_pvsp.png")
HOVER_PVSC_BUTTON = pygame.image.load("resources/images/hover_pvsc.png")
HOVER_SETTINGS_BUTTON = pygame.image.load("resources/images/hover_settings.png")
HOVER_EXIT_BUTTON = pygame.image.load("resources/images/hover_exit.png")
TICTAC = pygame.image.load("resources/images/tictactoe.png")
RECTANGLE = pygame.image.load("resources/images/rectangle.png")
BACKGROUND = pygame.image.load("resources/images/bg_color.png")

# Settings
DIF1_BUTTON = pygame.image.load("resources/images/dif_1.png")
DIF2_BUTTON = pygame.image.load("resources/images/dif_2.png")
DIF3_BUTTON = pygame.image.load("resources/images/dif_3.png")
HOVER_DIF1_BUTTON = pygame.image.load("resources/images/hover_dif1.png")
HOVER_DIF2_BUTTON = pygame.image.load("resources/images/hover_dif2.png")
HOVER_DIF3_BUTTON = pygame.image.load("resources/images/hover_dif3.png")
GRID10_BUTTON = pygame.image.load("resources/images/grid10.png")
GRID15_BUTTON = pygame.image.load("resources/images/grid15.png")
GRID20_BUTTON = pygame.image.load("resources/images/grid20.png")
HOVER_GRID10_BUTTON = pygame.image.load("resources/images/hover_grid10.png")
HOVER_GRID15_BUTTON = pygame.image.load("resources/images/hover_grid15.png")
HOVER_GRID20_BUTTON = pygame.image.load("resources/images/hover_grid20.png")
CIRCLE_BUTTON = pygame.image.load("resources/images/circle_button.png")
CROSS_BUTTON = pygame.image.load("resources/images/cross_button.png")
HOVER_CIRCLE_BUTTON = pygame.image.load("resources/images/hover_circle_button.png")
HOVER_CROSS_BUTTON = pygame.image.load("resources/images/hover_cross_button.png")
SAVE_BUTTON = pygame.image.load("resources/images/save.png")
RESET_BUTTON = pygame.image.load("resources/images/reset.png")
HOVER_RESET_BUTTON = pygame.image.load("resources/images/hover_reset.png")
HOVER_SAVE_BUTTON = pygame.image.load("resources/images/hover_save.png")
